events {}

http {
    upstream user-services {
        server user-service:8080;
    }

    upstream search-services {
        server search-service:8080;
    }

    upstream booking-services {
        server booking-service:8080;
    }

    server {
        listen 80;

        location /api/users {
            proxy_pass http://user-services;
        }
        location /api/search {
            proxy_pass http://search-services;
        }
        location /api/bookings {
            proxy_pass http://booking-services;
        }
    }
}