spring:
  application:
    name: search-service
  mongodb:
    uri: ${HOTEL_MONGO_URI:mongodb://localhost:27017/continental}
server:
  tomcat:
    accesslog:
      enabled: true
      pattern: "%h %l %u %t \"%r\" %s %b %D"
      directory: /dev/stdout